# =============================================================================
# SECRETS.TOML PARA STREAMLIT CLOUD - DASHBOARD PIPEFY KANASTRA
# =============================================================================
# COLE TODO ESTE CONTEÃšDO EM: Settings > Secrets no Streamlit Cloud
# =============================================================================

[santander_fundos]
# Certificados compartilhados (todos os fundos usam o mesmo)
cert_pem = """-----BEGIN CERTIFICATE-----
MIIH2DCCBcCgAwIBAgIIGCJ3s92KlQYwDQYJKoZIhvcNAQELBQAwdDELMAkGA1UE
BhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEg
ZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEYMBYGA1UEAxMPQUMg
VkFMSUQgUkZCIHY1MB4XDTI1MTEwNTE3MzcwNFoXDTI2MTEwNTE3MzcwNFowggES
MQswCQYDVQQGEwJCUjETMBEGA1UEChMKSUNQLUJyYXNpbDE2MDQGA1UECxMtU2Vj
cmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMRUwEwYD
VQQLEwxSRkIgZS1DUEYgQTExGDAWBgNVBAsTD0FDIFZBTElEIFJGQiBWNTEiMCAG
A1UECxMZQVIgSkwgQ0VSVElGSUNBRE8gRElHSVRBTDEZMBcGA1UECxMQVmlkZW9j
b25mZXJlbmNpYTEXMBUGA1UECxMOMjY1NDY4MjgwMDAxMzMxLTArBgNVBAMTJEdV
U1RBVk8gUFJPTUVUVEkgTUFTQ1VMSToxNDY2MzE1MDY3NTCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBANFG/sgBShNnymzg17MSqLWluskkJkkWeRlmEFQ2
EPHSoT/MkLkcX4U0gnCueQ14aAqhXVXyUp3u1ExmsmNcpA+/o/ubnAHG4cK5t4MC
dModwO5ibI9vU/RbWbjpCuZW27fpNwuauLlJBEPd35tUzCd8qntqKRlOK3inwx30
mkYhus7kYG0n4SsxnNn8SX3ZODBGhLLceHsPQNU+FAYPV4uiXaELeZg42FUDQ9TA
+84u59zNqQJLyviLinY+1SrzUYEdOzdCN3AJN3nLZt2TKj4SnlYOeyU0vyVVWiFn
gpdaod9DDXFJfgbSZHvmuHRP3RRTPzhrj5O09dS4m9mJMqMCAwEAAaOCAswwggLI
MIGcBggrBgEFBQcBAQSBjzCBjDBVBggrBgEFBQcwAoZJaHR0cDovL2ljcC1icmFz
aWwudmFsaWRjZXJ0aWZpY2Fkb3JhLmNvbS5ici9hYy12YWxpZHJmYi9hYy12YWxp
ZHJmYnY1LnA3YjAzBggrBgEFBQcwAYYnaHR0cDovL29jc3B2NS52YWxpZGNlcnRp
ZmljYWRvcmEuY29tLmJyMAkGA1UdEwQCMAAwHwYDVR0jBBgwFoAUU8ul5HVQmUAs
vlsVRcm+yzCqicUwcAYDVR0gBGkwZzBlBgZgTAECASUwWzBZBggrBgEFBQcCARZN
aHR0cDovL2ljcC1icmFzaWwudmFsaWRjZXJ0aWZpY2Fkb3JhLmNvbS5ici9hYy12
YWxpZHJmYi9kcGMtYWMtdmFsaWRyZmJWNS5wZGYwgbYGA1UdHwSBrjCBqzBToFGg
T4ZNaHR0cDovL2ljcC1icmFzaWwudmFsaWRjZXJ0aWZpY2Fkb3JhLmNvbS5ici9h
Yy12YWxpZHJmYi9sY3ItYWMtdmFsaWRyZmJ2NS5jcmwwVKBSoFCGTmh0dHA6Ly9p
Y3AtYnJhc2lsMi52YWxpZGNlcnRpZmljYWRvcmEuY29tLmJyL2FjLXZhbGlkcmZi
L2xjci1hYy12YWxpZHJmYnY1LmNybDAOBgNVHQ8BAf8EBAMCBeAwHQYDVR0lBBYw
FAYIKwYBBQUHAwIGCCsGAQUFBwMEMIGgBgNVHREEgZgwgZWBIGd1c3Rhdm8ucHJv
bWV0dGlAa2FuYXN0cmEuY29tLmJyoDgGBWBMAQMBoC8ELTE0MDYyMDAwMTQ2NjMx
NTA2NzUwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMKAXBgVgTAEDBqAOBAwwMDAw
MDAwMDAwMDCgHgYFYEwBAwWgFQQTMDAwMDAwMDAwMDAwMDAwMDAwMDANBgkqhkiG
9w0BAQsFAAOCAgEAHvReDaMo22km51BotHe+qopeyPK6oGTM42LoCazJCZ3sYb1L
8Hx5GIQFeatlrGJZPCaT6MUqH6r3qR6sjJzzNOgt93qFQC7AZGSTKHUP1H1OrkZb
uYUULa947MwiusY+u9dTH6PHQytBgrzyc3i82qachkprv2aQn2HY2UzBjeAHw3Tv
RqQ1BF4Wt3f4F5Snc4L5wkHMRpFIBWFLr8C/8fWzcHdsVp/J335V6KDXaeTVRaHK
fA/RpJ7vblCZxBGi0u/FC3v5w0UrrYJktVqbaiurltk0OnelFB3pUg6tVr4iKLIV
0QQot75KMl3KGJTN63CHPyK7r2G91hcA1VD/zwqCizZdmhj8Ec4bZo3Is8lTRHUW
WDIPm7OxEB+yBCATqEOYTAxyu2krfiRQbXSt/WD9hkOPhQlmEg61ynR9eki5I3IU
Kg1Hof4Ovb3MpX9mA/cPyT1phdGRC7fsvEUzCj4/HKxhYcSWfEltFGXwVvSCcCGq
KVeQzoB4mdDwJ7VOzKqX8RACUAIlZjxBQ6l55wBoLiSLmSuC03IoHp+I/SUFYod+
8IbmZrCqGQVJrYN0UB8nZjSfPQBn2qOr0R7rt3L9S0Tfr2Y9Mh5awDt5X4jemoOv
XU9hHfO8G1Od05bIsIvDNTwJ/Y1TxSZY7hpXK6hAHF4aL/p4mk3TcolNmyg=
-----END CERTIFICATE-----
"""

key_pem = """-----BEGIN RSA PRIVATE KEY-----
MIIEpgIBAAKCAQEA0Ub+yAFKE2fKbODXsxKotaW6ySQmSRZ5GWYQVDYQ8dKhP8yQ
uRxfhTSCcK55DXhoCqFdVfJSne7UTGayY1ykD7+j+5ucAcbhwrm3gwJ0yh3A7mJs
j29T9FtZuOkK5lbbt+k3C5q4uUkEQ93fm1TMJ3yqe2opGU4reKfDHfSaRiG6zuRg
bSfhKzGc2fxJfdk4MEaEstx4ew9A1T4UBg9Xi6JdoQt5mDjYVQND1MD7zi7n3M2p
AkvK+IuKdj7VKvNRgR07N0I3cAk3ectm3ZMqPhKeVg57JTS/JVVaIWeCl1qh30MN
cUl+BtJke+a4dE/dFFM/OGuPk7T11Lib2YkyowIDAQABAoIBAQCQA2YS5mg+YF85
e6STs1Rr5AdcoUbDZvag1s6H1MjmUIbsa25wJClLdi4JMtdUwLYAErkzCtV1n0Ny
6/z4SWkQ+VT0MUozItR69uhk/Ey4Ra9dnFeOgRLqBe8BQ0Vf6we6UH+zuZ5Cyw9n
UIiu0LTIu45p7U0o/9UEa5XmyEtd1FpmzHULvMluScDbqnYiKaa/cjk1ZM6qhz+C
vxtLuaus3yQL//bXx0CNv7DyAGzlsVQV1AzTdNant/c+0Y1uwLUZo7GB9uPkmIQ0
8PgZfBBUX+T4QM7pTZLLIogSPrSaiqlbxeMiEw2TOUbfI3lpRDBCjn6srpUWtqwu
ky7HVMX5AoGBANN5eDqxM5b59zX3KvL6irTd5PcBIbVNIyp3mXbdcytwXFOHYySX
OHsWPKQN40MCJaY+akSkrsTuZeed1O3lTNHd5x1/Ra4VZUCZ5uRzyPLZPyNM0BkU
VoNUApoZ2JKir9v6MlfAQQco6fpmrswTtUcAD/Amilw/RKi9QlZKIS7tAoGBAP1X
GQjP1AqNwhKeEatzdw9dHYSjC2sF4aGXRaLY61PSPIPRiHuPOpFzeWSLmjUTUbGy
xvDpFZ47bQ6KDVez61qqSQ099txnGQ12zHmuLC5GapWeK8ZfeN6fygQLoS0sn6AJ
Ua06beXeBbFWHWIP3XCdyVa3BwYPEZi+zNuHHCXPAoGBAMDMPI2d4j/h0rzTg8eU
HYM5zbZXxMiK8+WStkoFKSvQO4w3oW7Jo0eshUq4EpqTyYlf2/iK/38xLZzVazwc
UkX/feaJkxhcDzyvUy6yVOD6qTJgpFRJE3qVy+18ZNODGLt/xgf0khSZ+387wF70
FNAPQXibWocxc0I3kdQjr08dAoGBAL7pItF0JFtrpkN3YONuGNu4FOV+JL2a6gRm
xbBJfVVmSfogLZTHQ6CWf3VYinXSwC6EBc1IKOVb7PwW5qUfzY0+Y9yZxG0lOEjg
LIjJyzt4Dxv+3QgZrDFAAvF3fhdX2Fa2jxlWvbiKzolr1qquP/Z8wVwagy16r40G
w8PvFjQbAoGBAMQ4BfCVDTpfjU8ndc+PRujP+g2oSxwm7qdmKzv0XGjRxxbHYclp
WAPewqqKHs2IqpAGAAb4H4AcvEGJOstSl9hPX3/P2g3egwXDANV3H0lDIe6LJ/bR
udCi42ELNorZ84NvJBeGheiXkek/PRHr6kqCNcuPNmNssaf+bRWYfp33
-----END RSA PRIVATE KEY-----
"""

# =============================================================================
# FUNDOS SANTANDER (39 fundos)
# =============================================================================

[santander_fundos."911_BANK"]
nome = "911 BANK MULTI ESTRATEGIA FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "50.790.524/0001-00"
client_id = "3ZYICW0BDAwihhCwP4Tx08EtKYHFb2JG"
client_secret = "dAsx4AFNd7gNe8Lt"

[santander_fundos.ALBATROZ]
nome = "ALBATROZ FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS MULTISSETORIAL"
cnpj = "25.354.081/0001-59"
client_id = "tVgp6LU2OBZo62hXgBVt5AuMK3Z9sGSI"
client_secret = "KgMNdmARoqCfnMKC"

[santander_fundos.AMPLIC]
nome = "AMPLIC FUNDO DE INVESTIMENTO EM DIREITOS"
cnpj = "32.933.119/0001-03"
client_id = "ZcgN5NihardpebHHfewXrebGdnEH7dAk"
client_secret = "qKapajRKdLXeTyGp"

[santander_fundos."CONDOLIVRE FIDC"]
nome = "CONDOLIVRE FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "42.317.295/0001-74"
client_id = "WUrgXgftrP3G9iZXXIqljABiFx9oRBUC"
client_secret = "e4FAtyTG6mbDKPFV"

[santander_fundos."AUTO X"]
nome = "FUNDO DE INV EM DIREITOS CREDITORIOS CREDITAS AUTO X RESPONSABILIDADE LTDA"
cnpj = "53.095.241/0001-28"
client_id = "UWfbwD1F9TIaciza9vDMT9G2fAeOXK5x"
client_secret = "FanZS0KOL3gIgpTy"

[santander_fundos."AUTO XI FIDC"]
nome = "FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS CREDITAS AUTO XI"
cnpj = "58.035.124/0001-92"
client_id = "Ts21bGPsosCjh0SVeZrLDXefd0Tkn12Z"
client_secret = "JwLavIQKYQlJDAeo"

[santander_fundos."TEMPUS III FIDC"]
nome = "FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS NAO PADRONIZADOS CREDITAS TEMPUS III"
cnpj = "49.691.846/0001-04"
client_id = "7oyA8tfTt0lJTn04cPc5e7OMncoM0Ttw"
client_secret = "Q08pRGWaP1paZy70"

[santander_fundos.INOVA]
nome = "INOVA CREDITECH III FIDC SEGMENTO MULTICARTEIRA DE RESPONSABILIDADE LIMITADA"
cnpj = "52.340.225/0001-90"
client_id = "SkCHkZ4HTqVh33FAdXVolhOKBhJo8Ccf"
client_secret = "G3Adg7yMsVnW4fT2"

[santander_fundos.MAKENA]
nome = "MAKENA FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS NAO PADRONIZADO"
cnpj = "45.938.235/0001-67"
client_id = "6RYSAWrbfS5oGKvGfIom7gyemqZDtGmu"
client_secret = "Gl7x4FzaAyb4j2w6"

[santander_fundos.SEJA]
nome = "SEJA FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "24.987.402/0001-90"
client_id = "AUkiz79AzIzOWCmrPlTJG1mrallQDGTj"
client_secret = "2GYZYfWZMb0TVm4O"

[santander_fundos.AKIREDE]
nome = "AKI REDE FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "52.200.745/0001-06"
client_id = "jGodGw5UYmHFN2AfUDrjn59rQ3rfG8ii"
client_secret = "e3m9ALPlFJ3CImWy"

[santander_fundos.ATICCA]
nome = "ATICCA DIGITAL FUNDO DE INVESTIMENTO EMDIREITOS CREDITORIOS"
cnpj = "47.425.860/0001-30"
client_id = "jAn2GjinMON6PqGe1Xd55AtGMEEEMNzk"
client_secret = "BKCAUBHAhYmjG6sC"

[santander_fundos.ALTLEGAL]
nome = "ALT LEGAL CLAIMS FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "59.111.770/0001-54"
client_id = "yh8d7AxCeAczNx9JCGlDNfhi6UAbjJ3W"
client_secret = "tYv3gv1OHpG9VGmw"

[santander_fundos.NETMONEY]
nome = "NETMONEY FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "50.824.501/0001-60"
client_id = "khml0Jbohydfk8Y4wVIfAUN3odLR8g0Y"
client_secret = "5phosEtGQUal385F"

[santander_fundos.TCG]
nome = "TCG FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "58.304.663/0001-80"
client_id = "t8pceOLapDsFJ6AElE82cNyG1lfYFS0m"
client_secret = "3s4HeOVhpJvkf7iw"

[santander_fundos.DORO]
nome = "D'ORO CAPITAL FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOSMULTISSETORIAL"
cnpj = "51.731.270/0001-03"
client_id = "FXA6APtdbJswLzEuDfHT19ZwiCZQgEzK"
client_secret = "rGgUx8ceBVHfC0Cu"

[santander_fundos.ORION]
nome = "ORION JN FUNDO DE INV EM DIREITOS CREDITORIOS NAO-PADRONIZADOS MULTISSETORIAL"
cnpj = "38.057.973/0001-30"
client_id = "quT8mOWAhnDy98453Z2T7QxAK9dkLhNq"
client_secret = "MZ7yzwAGfwhaA9P0"

[santander_fundos.AGA]
nome = "AGA FUNDO DE INV EM DIREITOS CREDITORIOSNAO-PADRONIZADOS MULTISSETORIAL"
cnpj = "24.080.647/0001-39"
client_id = "cOHqYxoQCrMmsvFpGU9PC936GYzg2PBW"
client_secret = "D5j2RAKM8ESJDd8g"

[santander_fundos.PRIME]
nome = "PRIME FUNDO DE INVESTIMENTO EM DIREITOSCREDITORIOS MULTISSETORIAL"
cnpj = "20.905.862/0001-70"
client_id = "Qpb96NXSyle6ojA6roTMupt8U2CPdEiT"
client_secret = "Au4FnnIw1DloVEdl"

[santander_fundos.TESLA]
nome = "TESLA FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS MULTISSETORIAL"
cnpj = "51.732.995/0001-16"
client_id = "MD1dFLBv62AV8tAioBgiHwU2F0h8XGDH"
client_secret = "zJUMHBNP6SaW4ntA"

[santander_fundos.ALTINVEST]
nome = "ALTINVEST FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "58.888.944/0001-27"
client_id = "ieHHqhhTfLSJGrGAwKtgF1zaiQMRD97v"
client_secret = "ZcCXPG5z6IRD8ofY"

[santander_fundos.ANTARES]
nome = "ANTARES FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "60.078.440/0001-93"
client_id = "RAOBLb4L3M7jkAA0GNUjTh14GnwOA37R"
client_secret = "cHG1lRMIVfnhg8yV"

[santander_fundos.AV_CAPITAL]
nome = "AV CAPITAL FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "51.313.788/0001-27"
client_id = "BpmDhrmwNaq70IIeXJwH1hdnKtFSLAF8"
client_secret = "StnmdhBpSA7nUmFi"

[santander_fundos.BAY]
nome = "BAY FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "60.252.007/0001-22"
client_id = "dAfbuCpzagckdr5rg6DAI3aH8z8u1v6N"
client_secret = "Fu6uJXmJIbGl9qWG"

[santander_fundos.BLIPS]
nome = "BLIPS FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS - RESPONSABILIDADE LIMITADA"
cnpj = "58.482.694/0001-20"
client_id = "r4tqPLeZmomOjhuvroPQs94LZpAHp89H"
client_secret = "vaHpJNjsujpI34Yp"

[santander_fundos.COINVEST]
nome = "COINVEST FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "39.851.520/0001-43"
client_id = "ejgMPY9vkeOAVQoIEJGDGNsxLCojLUxA"
client_secret = "o5oA6kMGbHGTxjKj"

[santander_fundos.EXT_LOOMY]
nome = "EXT LOOMY FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS RESPONSABILIDADE LTDA"
cnpj = "61.062.538/0001-15"
client_id = "kELiN4rMxRGvT87lGlgTjUsWKGqptAJz"
client_secret = "LjNwu84IrYAFQ2Yw"

[santander_fundos.CONSORCIEI]
nome = "FUNDO DE INV EM COTAS DE FUNDOS DE INV EM DIREITOS CREDITORIOS CONSORCIEI 0"
cnpj = "60.115.778/0001-78"
client_id = "9Koio458B0Ldmj22KIPGBaaCQTVXXkNt"
client_secret = "AU8Sz6s6HBPWsu3V"

[santander_fundos.IGAPORA]
nome = "IGAPORA FUNDO DE INV EM COTAS DE FUNDOS DE INV MULTIMERCADO CREDIT PRIVADO LIVRE"
cnpj = "51.861.413/0001-00"
client_id = "SNSIPz2vPflTpGG4mXsV2wiyKYA9tqDB"
client_secret = "CdsEomBNz2sg4uqU"

[santander_fundos.LAVOURA]
nome = "LAVOURA FIAGRO - DIREITOS CREDITORIOS"
cnpj = "61.007.751/0001-24"
client_id = "GE4Tk4OwrHeSR09zdWGHQhr5qvBoc4Qt"
client_secret = "9ixjmnlRfYGWUDnR"

[santander_fundos.MACAUBAS]
nome = "MACAUBAS FUNDO DE INVESTIMENTO EM PARTICIPACOES MULTIESTRATEGIA"
cnpj = "56.960.033/0001-38"
client_id = "FpikkANTNekz9woA7ix942j71EAqcufB"
client_secret = "978wwHvAWOdEnUsU"

[santander_fundos."MARCA I"]
nome = "MARCA I FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS NAO PADRONIZADO"
cnpj = "49.466.992/0001-36"
client_id = "N3PPK8MGGaY5IYhu2AbwNAhwabcwaK0c"
client_secret = "gdyqcXgSUkEPkSxl"

[santander_fundos.NX_BOATS]
nome = "NX BOATS FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "61.430.639/0001-00"
client_id = "32TKKJOIEAIepS3fwJ3jA2V8SZLKZALC"
client_secret = "1T41mC3gzIKNoMek"

[santander_fundos.OKLAHOMA]
nome = "OKLAHOMA FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "57.976.577/0001-50"
client_id = "xAytHPeZuujFPGhaEqn1tAYtq2JWXnxs"
client_secret = "wCBd6OuAUK9UXeer"

[santander_fundos.ONCRED]
nome = "ONCRED FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "60.368.384/0001-21"
client_id = "TwndCMBA7DelsmPTeRKaRMfxR9bTQtq7"
client_secret = "1gt8ZQ1Gs7ZqcfCq"

[santander_fundos.ORIZ_JUS_CPS]
nome = "ORIZ JUS CPS FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "61.543.748/0001-25"
client_id = "gBl3S9CXD6e9qWjMVrGAG8FocE6MGI90"
client_secret = "x8hevWrq6IcdkoDL"

[santander_fundos.SIM]
nome = "SIM FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "60.681.487/0001-47"
client_id = "3ZAxFOOtrIYC1b6N46NGwRQ410yEsIO1"
client_secret = "SyxpmEOUvCqBgHjn"

[santander_fundos.SYMA]
nome = "SYMA FUNDO DE INVESTIMENTO FINANCEIRO MULTIMERCADO"
cnpj = "60.232.226/0001-40"
client_id = "Qrh2Frwdz6gAKLdIqzcMIGjd7HWsS6tD"
client_secret = "Ql6cMGC8OLHJxh6X"

[santander_fundos.YUNUS]
nome = "YUNUS NEGOCIOS SOCIAIS FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS"
cnpj = "29.330.482/0001-20"
client_id = "HdkMM1v16AKGRwhZsjG3qTG8dXaccUQL"
client_secret = "I8eMkGnnasdsLoXE"
